#!/usr/bin/python

import alfred
import json
import os
import subprocess
import sys
import urllib
import uuid


if __name__ == '__main__':
  '''
  Environment variables to be set by callers:

  Optional:
    - basedir: relative html paths will be resolved wrt this
               defaults to workflow dir

  Mandatory:
    - arg: the argument is passed to the script filter
  '''
  alfreditems = json.load(sys.stdin)
  gifHtml = alfreditems['items'][0]['gifHtml']

  bkgColor = alfred.theme()['window.color']
  bkgColorWithoutAlpha = bkgColor[:-2]

  # https://stackoverflow.com/a/50466440
  urllib.quote_plus = urllib.quote
  subprocess.call([
    'open', '-g',
    'alfred-gif-browser://update?%s' % urllib.urlencode({
      'gifHtml': gifHtml,
      'bkgColor': bkgColorWithoutAlpha
    })
  ])

  print(json.dumps(alfreditems, indent=2))
  sys.stdout.flush()
